# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/divide.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/sevenSegment.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/KeyBoard.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/Sech.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/Transition2.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/Transition.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/Shooter.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/SelectShip.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/Finish.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/compare.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/DotMatrix.sv}
  {C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/sources_1/new/TopModule.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Eren/Desktop/DIGITAL PROJECT/project_1.srcs/constrs_1/new/const.xdc}}]


synth_design -top TopModule -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TopModule.dcp

catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
